### PR TITLE
Add uninstall.php script to remove related files from mdl_files

### PR DESCRIPTION
**Pull request by vithushau**
Added  uninstall.php script to remove related files from the mdl_files table

### CODE REVIEW

**Comment by ScottVerbeek** [comment]
Couple items codechecker came back with for the file: 
```
FILE: /var/www/cqu-he/local/banner/db/uninstall.php
------------------------------------------------------------------------------------------------------------------------------------
FOUND 4 ERRORS AND 2 WARNINGS AFFECTING 6 LINES
------------------------------------------------------------------------------------------------------------------------------------
  1 | ERROR   | [x] End of line character is invalid; expected "\n" but found "\r\n" (Generic.Files.LineEndings.InvalidEOLChar)
 17 | ERROR   | [ ] Missing @copyright tag (moodle.Commenting.FileExpectedTags.CopyrightTagMissing)
 24 | WARNING | [ ] Unexpected MOODLE_INTERNAL check. No side effects or multiple artifacts detected.
    |         |     (moodle.Files.MoodleInternal.MoodleInternalNotNeeded)
 35 | WARNING | [x] Short array syntax must be used to define arrays (Generic.Arrays.DisallowLongArraySyntax.Found)
 36 | ERROR   | [x] Whitespace found at end of line (Squiz.WhiteSpace.SuperfluousWhitespace.EndLine)
 37 | ERROR   | [ ] Expected "foreach (...) {\n"; found "foreach(...) {\n" (moodle.ControlStructures.ControlSignature.Found)

```

**Comment by ScottVerbeek** [comment]
I squashed the merge into master, thanks @vithushau .

**Comment by danmarsden** [comment]
I'm confused why this isn't handled in core? - are the files stored in the wrong component?

**Comment by danmarsden** [comment]
@ScottVerbeek @vithushau this shouldn't be needed - core handles it here:
https://github.com/moodle/moodle/blob/main/lib/adminlib.php#L261

quite often when the uninstall process is triggered - the plugin codebase itself has already gone - so it doesn't often get the chance to trigger a plugins own uninstall.php anyway

**Pull request merged**
